/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTrainingRouteImport } from './routes/_authenticated/admin/training'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminNotesRouteImport } from './routes/_authenticated/admin/notes'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminGovernanceRouteImport } from './routes/_authenticated/admin/governance'
import { Route as AuthenticatedAdminFlightOpsRouteImport } from './routes/_authenticated/admin/flight-ops'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminCustomerRelationsRouteImport } from './routes/_authenticated/admin/customer-relations'
import { Route as AuthenticatedAdminComplianceRouteImport } from './routes/_authenticated/admin/compliance'
import { Route as AuthenticatedAdminBookkeepingRouteImport } from './routes/_authenticated/admin/bookkeeping'
import { Route as AuthenticatedAdminAcademyDashboardRouteImport } from './routes/_authenticated/admin/academy-dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTrainingRoute =
  AuthenticatedAdminTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotesRoute = AuthenticatedAdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGovernanceRoute =
  AuthenticatedAdminGovernanceRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFlightOpsRoute =
  AuthenticatedAdminFlightOpsRouteImport.update({
    id: '/flight-ops',
    path: '/flight-ops',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomerRelationsRoute =
  AuthenticatedAdminCustomerRelationsRouteImport.update({
    id: '/customer-relations',
    path: '/customer-relations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComplianceRoute =
  AuthenticatedAdminComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBookkeepingRoute =
  AuthenticatedAdminBookkeepingRouteImport.update({
    id: '/bookkeeping',
    path: '/bookkeeping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAcademyDashboardRoute =
  AuthenticatedAdminAcademyDashboardRouteImport.update({
    id: '/academy-dashboard',
    path: '/academy-dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/academy-dashboard': typeof AuthenticatedAdminAcademyDashboardRoute
  '/admin/bookkeeping': typeof AuthenticatedAdminBookkeepingRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/customer-relations': typeof AuthenticatedAdminCustomerRelationsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/flight-ops': typeof AuthenticatedAdminFlightOpsRoute
  '/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/training': typeof AuthenticatedAdminTrainingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/academy-dashboard': typeof AuthenticatedAdminAcademyDashboardRoute
  '/admin/bookkeeping': typeof AuthenticatedAdminBookkeepingRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/customer-relations': typeof AuthenticatedAdminCustomerRelationsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/flight-ops': typeof AuthenticatedAdminFlightOpsRoute
  '/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/training': typeof AuthenticatedAdminTrainingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/admin/academy-dashboard': typeof AuthenticatedAdminAcademyDashboardRoute
  '/_authenticated/admin/bookkeeping': typeof AuthenticatedAdminBookkeepingRoute
  '/_authenticated/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/_authenticated/admin/customer-relations': typeof AuthenticatedAdminCustomerRelationsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/flight-ops': typeof AuthenticatedAdminFlightOpsRoute
  '/_authenticated/admin/governance': typeof AuthenticatedAdminGovernanceRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/notes': typeof AuthenticatedAdminNotesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/training': typeof AuthenticatedAdminTrainingRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/portal'
    | '/admin/academy-dashboard'
    | '/admin/bookkeeping'
    | '/admin/compliance'
    | '/admin/customer-relations'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/flight-ops'
    | '/admin/governance'
    | '/admin/messages'
    | '/admin/notes'
    | '/admin/settings'
    | '/admin/training'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/portal'
    | '/admin/academy-dashboard'
    | '/admin/bookkeeping'
    | '/admin/compliance'
    | '/admin/customer-relations'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/flight-ops'
    | '/admin/governance'
    | '/admin/messages'
    | '/admin/notes'
    | '/admin/settings'
    | '/admin/training'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/admin/academy-dashboard'
    | '/_authenticated/admin/bookkeeping'
    | '/_authenticated/admin/compliance'
    | '/_authenticated/admin/customer-relations'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/flight-ops'
    | '/_authenticated/admin/governance'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/notes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/training'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/training': {
      id: '/_authenticated/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AuthenticatedAdminTrainingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notes': {
      id: '/_authenticated/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AuthenticatedAdminNotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/governance': {
      id: '/_authenticated/admin/governance'
      path: '/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AuthenticatedAdminGovernanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/flight-ops': {
      id: '/_authenticated/admin/flight-ops'
      path: '/flight-ops'
      fullPath: '/admin/flight-ops'
      preLoaderRoute: typeof AuthenticatedAdminFlightOpsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customer-relations': {
      id: '/_authenticated/admin/customer-relations'
      path: '/customer-relations'
      fullPath: '/admin/customer-relations'
      preLoaderRoute: typeof AuthenticatedAdminCustomerRelationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/compliance': {
      id: '/_authenticated/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AuthenticatedAdminComplianceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookkeeping': {
      id: '/_authenticated/admin/bookkeeping'
      path: '/bookkeeping'
      fullPath: '/admin/bookkeeping'
      preLoaderRoute: typeof AuthenticatedAdminBookkeepingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/academy-dashboard': {
      id: '/_authenticated/admin/academy-dashboard'
      path: '/academy-dashboard'
      fullPath: '/admin/academy-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminAcademyDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAcademyDashboardRoute: typeof AuthenticatedAdminAcademyDashboardRoute
  AuthenticatedAdminBookkeepingRoute: typeof AuthenticatedAdminBookkeepingRoute
  AuthenticatedAdminComplianceRoute: typeof AuthenticatedAdminComplianceRoute
  AuthenticatedAdminCustomerRelationsRoute: typeof AuthenticatedAdminCustomerRelationsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminFlightOpsRoute: typeof AuthenticatedAdminFlightOpsRoute
  AuthenticatedAdminGovernanceRoute: typeof AuthenticatedAdminGovernanceRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNotesRoute: typeof AuthenticatedAdminNotesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTrainingRoute: typeof AuthenticatedAdminTrainingRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAcademyDashboardRoute:
      AuthenticatedAdminAcademyDashboardRoute,
    AuthenticatedAdminBookkeepingRoute: AuthenticatedAdminBookkeepingRoute,
    AuthenticatedAdminComplianceRoute: AuthenticatedAdminComplianceRoute,
    AuthenticatedAdminCustomerRelationsRoute:
      AuthenticatedAdminCustomerRelationsRoute,
    AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminFlightOpsRoute: AuthenticatedAdminFlightOpsRoute,
    AuthenticatedAdminGovernanceRoute: AuthenticatedAdminGovernanceRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminNotesRoute: AuthenticatedAdminNotesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTrainingRoute: AuthenticatedAdminTrainingRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
